version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    env_file: "${WEB_ENV_FILE:-.env}"
  postgres:
    image: "postgres:14.3-alpine"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
